### ISSUE TITLE
Registro de Mentores - Sábado 8 de Septiembre, 2018

### ISSUE THREAD

**Issue by Xabadu** [nodeschool/santiago#17]
¡Hola 👋!

¡Tenemos nuevo evento!

Nuestro próximo NodeSchool será en Autofact el Sábado 8 de Septiembre de 11am a 3pm. La dirección es: Avenida Providencia 2019, Oficina A41, Providencia, Santiago -- Comenta abajo si tienes preguntas o quieres unirte como mentor.

Si estás pensando unirte como mentor, pero tienes dudas de si estás capacitado, ¡te aseguramos que si!. Déjanos un comentario y te ayudaremos en todo lo que podamos.

Lo que le pedimos a los Mentores:
- Completar los [workshoppers core de NodeSchool](http://nodeschool.io/#workshopper-list) antes del evento.
- Adicionalmente, completar alguno de los workshoppers electivos es un buen bonus ✌️(pero no es obligación).
- Revisar las [Buenas Prácticas de Mentores](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Llegar 30 minutos antes (10:30am) para hacer la reunión previa de mentores.

Mentores confirmados:
- [x] @DMaster69  
- [x] @highercomve 
- [x] @p1nox 
- [x] @jfgodoy 
- [x] @betacar 
- [ ] Tu? 

Organizadores:
- [x] @cristofer-dev 
- [x] @enbonnet
- [x] @Xabadu

¡Gracias por unirse! 🙌 

Link de registro para asistentes: https://www.meetup.com/es-ES/NodersJS/events/254225681/

**Comment by DMasterIO** [comment]
Chicos, cuenten conmigo como mentor!! ¿Cómo lo coordinamos?

Quedo atento.

**Comment by Xabadu** [comment]
Yaaas @DMaster69 🙌, gracias por unirte. Recuerda revisar los workshoppers core de NodeSchool antes del evento y llegar 30 minutos antes ese día para que hagamos la reunión previa de mentores, ahí les explicaremos la modalidad y que haremos durante ese día.

Si tienes alguna pregunta específica, no dudes en dejarla por acá.

![high-knive](https://user-images.githubusercontent.com/3161019/44939134-c7b2f200-ad37-11e8-9a2e-195971a56e0d.gif)

**Comment by cristofer-dev** [comment]
Genial @DMaster69 ! \o/

**Comment by highercomve** [comment]
Pueden contar conmigo!! 

Cuénteme cómo es todo :)

**Comment by Xabadu** [comment]
@highercomve 🙌, que grande!

Recuerda darle una mirada a los workshoppers core de NodeSchool (link arriba en el issue) y llegar 30 minutos antes ese día para la reunión previa de mentores. Fuera de tener en mente como son esos workshops no es necesario llevar nada más, solo ayudar a la gente con problemas que puedan tener mientras los resuelven (paciencia y harto debugging!)

![colbert](https://user-images.githubusercontent.com/3161019/44941328-dad1bc00-ad4f-11e8-8fa5-28be9d01cf70.gif)

**Comment by p1nox** [comment]
Cuenten conmigo ☺️

**Comment by Xabadu** [comment]
@p1nox 🙌✌️🤘- lo más grande, como siempre apoyando en todo. Gracias!

![yes-old-school](https://user-images.githubusercontent.com/3161019/44949064-b244d300-adde-11e8-9e24-9501dc55a6fb.gif)

**Comment by jfgodoy** [comment]
cuenten conmigo :+1:

**Comment by Xabadu** [comment]
@jfgodoy excelente! Gracias por unirte! Recuerda darle una mirada a los workshoppers core de NodeSchool (link arriba en el issue) y llegar 30 minutos antes ese día para la reunión previa de mentores.

Nos vemos el sábado!

![yeah-cage](https://user-images.githubusercontent.com/3161019/45183389-4efddb00-b1fa-11e8-8273-f3ed7c585f93.gif)

**Comment by betacar** [comment]
+1

**Comment by Xabadu** [comment]
@betacar nice! Gracias por sumarte dude! ✌️- Recuerda darle una mirada a los workshoppers core de NodeSchool (link arriba en el issue) y llegar 30 minutos antes ese día para la reunión previa de mentores.

Nos vemos el sábado!

**Comment by Xabadu** [comment]
Gracias a todos por ir! Fue un gran evento.

Nos vemos en el próximo! ✌️
