### ISSUE TITLE
International Day Event

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/santiago#2]
Hello guys, @feross  signed you up for the international day but it seems you havn't come around to setup an event site yet! See: nodeschool/international-day#22

**Comment by iancrowther** [comment]
is this event still happening?

**Comment by feross** [comment]
I didn't sign anyone up for international day.

**Comment by finnp** [comment]
lol, it's @forres

**Comment by martinheidegger** [comment]
Sorry for my typo @feross

**Comment by feross** [comment]
no problem :-)

**Comment by a0viedo** [comment]
this can only mean one thing...you should visit Chile @feross

**Comment by feross** [comment]
Haha, would love to! Lmk if there's a good conference and I'm happy to come!
