### ISSUE TITLE
Registro de Mentores - Sábado 6 de Octubre, 2018

### ISSUE THREAD

**Issue by enBonnet** [nodeschool/santiago#21]
¡Hola 👋!

¡Tenemos nuevo evento!

Nuestro próximo NodeSchool será en Autofact el Sábado 6 de Octubre de 2pm a 6pm. La dirección es: Avenida Providencia 2019, Oficina A41, Providencia, Santiago -- Comenta abajo si tienes preguntas o quieres unirte como mentor.

Si estás pensando unirte como mentor, pero tienes dudas de si estás capacitado, ¡te aseguramos que si!. Déjanos un comentario y te ayudaremos en todo lo que podamos.

Lo que le pedimos a los Mentores:
- Completar los [workshoppers core de NodeSchool](http://nodeschool.io/#workshopper-list) antes del evento.
- Adicionalmente, completar alguno de los workshoppers electivos es un buen bonus ✌️(pero no es obligación).
- Revisar las [Buenas Prácticas de Mentores](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Llegar 30 minutos antes (1:30pm) para hacer la reunión previa de mentores.

Mentores confirmados:

- [x] @cristianberroeta 
- [x] @felipealfonsog 
- [x] @highercomve
- [x] @p1nox
- [x] @estairt
- [ ] Tu? 

Organizadores:
- [x] @cristofer-dev 
- [x] @enbonnet

¡Gracias por unirse! 🙌 

Link de registro para asistentes: https://www.meetup.com/es-ES/NodersJS/events/255077850/

**Comment by enBonnet** [comment]
Hola @DMaster69 @highercomve @p1nox @jfgodoy @betacar,

Gracias a los que pudieron participar como mentores en la edición anterior, aquí esta abierto el registro de mentores para la próxima edición, muy agradecidos si pueden participar nuevamente.

![giphy](https://user-images.githubusercontent.com/13243693/46184974-6d616e80-c2ae-11e8-9658-37af1cf76fb7.gif)

**Comment by jfgodoy** [comment]
Me hubiera gustado participar nuevamente, pero estaré fuera de Santiago ese día. Para la próxima nos vemos :)

**Comment by enBonnet** [comment]
¡No hay problemas master @jfgodoy te esperamos para el próximo! Agradecido de todas formas

**Comment by cristianberroeta** [comment]
Hola @enBonnet,
Me gustaría participar como mentor.

**Comment by enBonnet** [comment]
¡Excelente @cristianberroeta nos vemos ese día!

¡Anotado!

**Comment by felipealfonsog** [comment]
Hola me interesa participar como mentor. .. :) estoy disponible... :+1:  Debo enviar algún email? Slds! :100:  :+1:

**Comment by enBonnet** [comment]
¡Woju! Excelente @felipealfonsog gracias por sumarte! Con este ya es suficiente, las recomendaciones son estar 30 minutos antes de comenzar y que revises los talleres de nodeschool que puedes encontrar en https://nodeschool.io/#workshopper-list

¡Te esperamos!

**Comment by highercomve** [comment]
Pueden contar conmigo!

Saludos

**Comment by highercomve** [comment]
Pueden contener conmigo :)

**Comment by enBonnet** [comment]
¡Ahora si se prendió esto! Gracias master @highercomve

**Comment by p1nox** [comment]
Me sumo tambien por aqui 👍

**Comment by enBonnet** [comment]
Vamos con todo. ¡@p1nox gracias por sumarte!

**Comment by estairt** [comment]
me sumo a mentor 🤓

**Comment by enBonnet** [comment]
¡Tremendo! Será un nodeschool top top top, gracias por sumarte @estairt 👏

**Comment by enBonnet** [comment]
¡Gracias por apoyo de nuevo!

@estairt @highercomve @cristianberroeta
