### ISSUE TITLE
Registro de Mentores - Sábado 27 de Abril, 2019

### ISSUE THREAD

**Issue by enBonnet** [nodeschool/santiago#25]
Hola 👋!

¡Tenemos nuevo evento!

Nuestro próximo NodeSchool será en Autofact el sábado 27 de Abril  partiendo a las  15:00 hasta las 19:00 horas. 
La dirección es: Av. Providencia 2019, Oficina 41A, Providencia, Santiago -- Comenta abajo si tienes preguntas o quieres unirte como mentor.

Si estás pensando unirte como mentor, pero tienes dudas de si estás capacitado, ¡te aseguramos que si!. Déjanos un comentario y te ayudaremos en todo lo que podamos.

Lo que le pedimos a los Mentores:
- Completar los [workshoppers core de NodeSchool](http://nodeschool.io/#workshopper-list) antes del evento.
- Adicionalmente, completar alguno de los workshoppers electivos es un buen bonus ✌️(pero no es obligación).
- Revisar las [Buenas Prácticas de Mentores](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Llegar 30 minutos antes para hacer la reunión previa de mentores.

Mentores confirmados:

- [x] @p1nox
- [x] @jfgodoy
- [x] @Pillin 
- [x] @jacobparra
- [ ] Tu? 

Organizador:
- [x] @enbonnet

¡Gracias por unirse! 🙌 

Link de registro para asistentes: https://www.meetup.com/es-ES/NodersJS/events/260698721/

**Comment by p1nox** [comment]
Respondiendo el llamado por aqui 😃 👍

**Comment by enBonnet** [comment]
Gracias por sumarte @p1nox

**Comment by jfgodoy** [comment]
me anoto también

**Comment by enBonnet** [comment]
Tremendo, @jfgodoy gracias por sumarte una vez más.

**Comment by Pillin** [comment]
Hola!, también me sumo! :)

**Comment by enBonnet** [comment]
Wojo! Gracias por sumarte @Pillin 
![tumblr_lxpafdfEZ31rn95k2o1_250](https://user-images.githubusercontent.com/13243693/56590116-81571f80-65b4-11e9-95a7-345120f0a295.gif)

**Comment by jacobparra** [comment]
Epale! +1 por aquí :)

**Comment by enBonnet** [comment]
Tremendo! Gracias @jacobparra por sumarte!

**Comment by enBonnet** [comment]
¡Gracias a todos por sumarse!
