### ISSUE TITLE
Registro de Mentores - Sábado 11 de Mayo, 2019

### ISSUE THREAD

**Issue by enBonnet** [nodeschool/santiago#26]
Hola 👋!

¡Tenemos nuevo evento!

Nuestro próximo NodeSchool será en [23people](https://23people.io/) el sábado 11 de Mayo  partiendo a las  11:00 hasta las 15:00 horas. 
La dirección es: Av. Providencia 1208, Oficina 306, Providencia, Santiago -- Comenta abajo si tienes preguntas o quieres unirte como mentor.

Si estás pensando unirte como mentor, pero tienes dudas de si estás capacitado, ¡te aseguramos que si!. Déjanos un comentario y te ayudaremos en todo lo que podamos.

Lo que le pedimos a los Mentores:
- Completar los [workshoppers core de NodeSchool](http://nodeschool.io/#workshopper-list) antes del evento.
- Adicionalmente, completar alguno de los workshoppers electivos es un buen bonus ✌️(pero no es obligación).
- Revisar las [Buenas Prácticas de Mentores](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Llegar 30 minutos antes para hacer la reunión previa de mentores.

Mentores confirmados:

- [ ] Tu? 
- [x] @highercomve
- [x] @jfgodoy 
- [x] @flakolefluk 

Organizador:
- [x] @enbonnet

¡Gracias por unirse! 🙌 

Link de registro para asistentes: https://www.meetup.com/es-ES/NodersJS/events/261109932

**Comment by highercomve** [comment]
Quiero participar como mentor!!

**Comment by jfgodoy** [comment]
también me sumo.

**Comment by enBonnet** [comment]
Gracias! Tremendo que se sumen @highercomve @jfgodoy (¡Buena foto de perfil!)

**Comment by flakolefluk** [comment]
Me anoto como mentor. :)

**Comment by DiegoSepuSoto** [comment]
Hola! es primera vez que asistiré a uno de los eventos... Es necesario tener un nivel mínimo para participar? O puedo ir con mi maleta llena de sueños y dudas?

**Comment by enBonnet** [comment]
Gracias por sumarte como mentor @flakolefluk 😄

**Comment by enBonnet** [comment]
Hola @DiegoSepu97 para ser mentor solo tienes que tener conocimientos de nodejs y javascript con buena disposición para enseñar, guiar y compartir, te sumas como mentor?

**Comment by DiegoSepuSoto** [comment]
@enBonnet Muchas gracias por la respuesta; la verdad mi intención es ir como invitado, ya que aún me encuentro aprendiendo las cosas básicas... Pero recién me di cuenta que estoy preguntando en el lugar incorrecto 😅

**Comment by enBonnet** [comment]
Tranquilo @DiegoSepu97 todos los canales son validos para preguntar jajaja

**Comment by enBonnet** [comment]
Hola chic@s,

@p1nox @Pillin @jacobparra @betacar @jacobparra @lporras

Les hago tag en esta issue por si alguno quiere sumarse como mentor nuevamente, nos vendría bien un par de manos extras como siempre, pero no se sienten obligados igual los voy a seguir llevando en mi ❤️ . Es solo por si no de casualidad no han visto la issue 😄 

¡Saludos!

**Comment by lporras** [comment]
Hola @enBonnet me sumo como mentor!

**Comment by enBonnet** [comment]
Gracias a los que asistieron! Ya estoy programando el del próximo mes y allí les estaré avisando 😄
