### ISSUE TITLE
Registro de Mentores - Sábado 29 de junio, 2019

### ISSUE THREAD

**Issue by enBonnet** [nodeschool/santiago#27]
Hola 👋!

¡Tenemos nuevo evento!

Nuestro próximo NodeSchool será en [23people](https://23people.io/) el sábado 29 de junio  partiendo a las  15:00 hasta las 19:00 horas. 
La dirección es: Av. Providencia 1208, Oficina 306, Providencia, Santiago -- Comenta abajo si tienes preguntas o quieres unirte como mentor.

Si estás pensando unirte como mentor, pero tienes dudas de si estás capacitado, ¡te aseguramos que si!. Déjanos un comentario y te ayudaremos en todo lo que podamos.

Lo que le pedimos a los Mentores:
- Completar los [workshoppers core de NodeSchool](http://nodeschool.io/#workshopper-list) antes del evento.
- Adicionalmente, completar alguno de los workshoppers electivos es un buen bonus ✌️(pero no es obligación).
- Revisar las [Buenas Prácticas de Mentores](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Llegar 30 minutos antes para hacer la reunión previa de mentores.

Mentores confirmados:

- [ ] Tu? 
- [x] @jfgodoy 
- [x] @Pillin
- [x] @davidlaym
- [x] @nicolascine
- [x] @flakolefluk
- [x] @lporras

Organizador:
- [x] @enbonnet

¡Gracias por unirse! 🙌 

Link de registro para asistentes: https://www.meetup.com/es-ES/NodersJS/events/262401933

**Comment by jfgodoy** [comment]
Hola Ender, me sumo.

**Comment by Pillin** [comment]
+1 =)

**Comment by enBonnet** [comment]
Wojo! Tremendo! Gracias por sumarse una vez más! @jfgodoy y @Pillin 

![giphy](https://user-images.githubusercontent.com/13243693/59767211-cb384b00-926f-11e9-8048-259b041d2b98.gif)

**Comment by davidlaym** [comment]
me sumo!

**Comment by enBonnet** [comment]
Tremendo @davidlaym gracias por sumarte!

![surprise](https://user-images.githubusercontent.com/13243693/59860448-ce553900-934c-11e9-8da6-0c583a8940b3.gif)

**Comment by nicolascine** [comment]
@enBonnet, me sumo igual 👍

**Comment by enBonnet** [comment]
Genial @nicolascine gracias por sumarte!

![MarriedHorribleCrayfish-size_restricted](https://user-images.githubusercontent.com/13243693/59946053-6a5b6f00-9437-11e9-93e0-31bf7f2b7594.gif)

**Comment by flakolefluk** [comment]
Me sumo! Nos vemos :)

**Comment by enBonnet** [comment]
Tremendisimo @flakolefluk gracias por sumarte una vez más! 
![dance_gif](https://user-images.githubusercontent.com/13243693/60066010-d1954f80-96d3-11e9-9de7-94e7f759de6d.gif)

**Comment by lporras** [comment]
Me sumo! Saludos

**Comment by enBonnet** [comment]
¡Tremendo @lporras gracias por sumarte!
![tenor](https://user-images.githubusercontent.com/13243693/60130132-a444b200-9764-11e9-8dba-f23b56672a1d.gif)

**Comment by enBonnet** [comment]
Gracias a todos por participar y registrarse igual a los que no pudieron asistir por diferentes motivos, los espero en los próximos! @jfgodoy @Pillin @davidlaym @nicolascine @flakolefluk @lporras

**Comment by lporras** [comment]
👍
