### ISSUE TITLE
Registro de Mentores para NodeSchool Febrero 2016

### ISSUE THREAD

**Issue by fforres** [nodeschool/santiago#5]
Estamos esperando cerca de 60+ Asistentes, por lo que necesitaremos -+ 12 mentores
- Los mentores deben haber terminado los core workshops de [NodeSchool](http://nodeschool.io) antes del evento. 
- **_Completar otros workshops solo los vuelve más cool :smiley:**_
- Es recomendado que los mentores lean la sección de la wiki [Event Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices)
### Core Courses

![image](https://cloud.githubusercontent.com/assets/952992/12380216/1e700896-bd4c-11e5-8172-aaeeaef090dd.png)
#### Mentores Confirmados (9)
- [x] @LasagnaAndroid
- [x] @satanas 
- [x] @tangzero 
- [x] @lintuxt 
- [x] @svchost
- [x] @RaulCifuentes,
- [x] @p1nox 
- [x] @hombrebacalao 
- [x] @guerrerocarlos 
- [x] @highercomve 
- [x] @jeloou 
- [x] @betacar 
- [x] tu?
#### Organizadores y voluntarios
- [x] @fforres
- [x] @xabadu
- [x] @comunacho
- [x] @jorgevenegas

Si quieres inscribirte, déjanos tu correo para contactarte  (Si quieres, también tu twitter :smile_cat:  )

**Comment by adriansalgadoa** [comment]
Hola, a mi me gustaría ayudar, contactenme a adrian.salgado.a@gmail.com

**Comment by Xabadu** [comment]
@LasagnaAndroid buenísima!, quedas confirmado. Te contactaremos luego con los detalles para coordinar. 

Un abrazo!

**Comment by tangzero** [comment]
Si el @satanas participa, yo también participaré!

**Comment by lintuxt** [comment]
Hola, yo también quiero ayudar. Saludos.

**Comment by fforres** [comment]
Genial @tangzero  @lintuxt 

Off topic, @tangzero es el mega nick! :+1:

**Comment by RaulCifuentes** [comment]
Por favor me pueden confirmar el horario? Muchas gracias! andres.cifuentes@gmail.com

**Comment by Xabadu** [comment]
Hola @RaulCifuentes, el evento comienza a las 9:00 am. ¿Te sumas como mentor? Saludos!

**Comment by RaulCifuentes** [comment]
Gracias por la respuesta Fernando. Dale. Me sumo al mentoring.

**Comment by fforres** [comment]
Genial @RaulCifuentes, agregado :)

**Comment by p1nox** [comment]
Por aqui queriendo ayudar tambien :feelsgood: :+1:

**Comment by Xabadu** [comment]
Buenísima @p1nox! Agregado. Gracias!

**Comment by jarriagadat** [comment]
Epa!
Yo quiero ayudar!
[jarriagadatriana@gmail.com](url)

**Comment by Xabadu** [comment]
Excelente @hombrebacalao, te agregamos. Gracias!

**Comment by guerrerocarlos** [comment]
A mi tambien me gustaria participar :) 

Por favor incluyanme en la lista.

**Comment by Xabadu** [comment]
@guerrerocarlos agregado! Gracias por unirte :D

**Comment by guerrerocarlos** [comment]
A que hora empieza la organización del evento el Sábado? o incluso el día antes?

**Comment by fforres** [comment]
Esta semana enviaremos un correo para coordinar temas más específicos @guerrerocarlos :smile:  

Les vamos a notificar por acá, pero sería mejor que quedáramos por correo, les dejo el mío para que me envíen un "hola" y comunicarles todo por ahí. Un abrazo! 

felipe.torressepulveda@gmail.com

_(Massive Notification)_
@LasagnaAndroid @satanas @tangzero @lintuxt @svchost @RaulCifuentes @p1nox @hombrebacalao @guerrerocarlos

**Comment by highercomve** [comment]
Hey hey me anotó a ayudar con lo que pueda!! @highercomve higher.vnf@gmail.com

**Comment by Xabadu** [comment]
@highercomve agregado!, gracias por unirte.

**Comment by jeloou** [comment]
I'm in! :godmode: @_wthello, jnunez@groupon.com

**Comment by Xabadu** [comment]
@jeloou buenísima!, agregado :D

**Comment by jarriagadat** [comment]
Hola!
encontré este proyecto :: [codeology](http://codeology.braintreepayments.com/)
pueden colocar su usuario de github

Codeology is an open-source project that brings to life the art and science of code. An algorithm analyzes GitHub projects and creates unique organic forms based on the codebase size and language. As no two pieces of code are alike, no two Codeology forms are alike.

**Comment by betacar** [comment]
Me gustaría unirme as mentor. :)

**Comment by Xabadu** [comment]
@betacar perfect, te anoté. Déjanos tu correo para enviarte la info :D

**Comment by betacar** [comment]
@Xabadu carbetacar [at] gmail

**Comment by jfgodoy** [comment]
Hola, también me gustaría participar como mentor

**Comment by pamo** [comment]
Hola 👋 
Se que este evento ya paso, pero como me sumo para ayudar con el proximo? 👓

**Comment by Xabadu** [comment]
Hola @pamo! Gracias por las ganas de ayudar. Apenas tengamos claridad del próximo avisaremos vía Twitter en @nodeschoolstgo y abriremos un nuevo issue para los registros ;)
