### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by fforres** [nodeschool/santiago#6]
La información de como hacer un logo está acá.
@jorgevenegas  @Xabadu @comunacho 

https://github.com/nodeschool/nodeschool.github.io/tree/source/images/make-a-sticker

Acá subí un Logo que armé para tener una idea solamente
![image](https://cloud.githubusercontent.com/assets/952992/12603698/ba55d67a-c493-11e5-9826-ba35d904bf2b.png)

(Acá el link al svg) https://github.com/nodeschool/Santiago/blob/gh-pages/images/STGO.svg

**Comment by fforres** [comment]
Also,
Acá hay los medios logos https://github.com/nodeschool/nodeschool.github.io/tree/source/images

**Comment by fforres** [comment]
Deberíamos hacer algunos con el logo nuestro, y otros con este :D
![image](https://cloud.githubusercontent.com/assets/952992/12603899/608e4e40-c495-11e5-8b65-d7787b6a0a91.png)
https://github.com/nodeschool/nodeschool.github.io/blob/source/images/nodeschool-hex.svg

**Comment by fforres** [comment]
Algo como esto? 

Con la bandera de chile detrás? :D

![4338_normal_1416512970_nodeschool-osaka-badge](https://cloud.githubusercontent.com/assets/952992/12738554/79318c64-c940-11e5-9dac-74d84ad2dc1c.png)

**Comment by Xabadu** [comment]
Me gusta. ¿Tienes por ahí algún editable? Quizás pueda armar algo.

**Comment by fforres** [comment]
pta... No :(
Es solo una idea @Xabadu 
Tenemos el SVG del logo de arriba solamente

https://github.com/nodeschool/Santiago/blob/gh-pages/images/STGO.svg

**Comment by Xabadu** [comment]
Cerrando este por ahora, ya que están usando el logo hecho por @cristofer-dev (que está 👌)
